// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
// Import all available fonts for AI usage
import "../lib/fonts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Kimaaki – Marketplace de Delivery em Angola, Moçambique, Cabo Verde e Guiné-Bissau",
  description: "Kimaaki conecta você a restaurantes, supermercados, lojas e farmácias. Faça seu pedido pelo app e receba onde estiver.",
  keywords: "Kimaaki, delivery Angola, delivery Moçambique, marketplace de entregas, app de comida, supermercados online, delivery Cabo Verde, delivery Guiné-Bissau, entrega rápida, pedidos online",
  openGraph: {
    title: "Kimaaki – Marketplace de Delivery em Angola, Moçambique, Cabo Verde e Guiné-Bissau",
    description: "O marketplace de entregas que conecta você a restaurantes, supermercados e farmácias na sua cidade",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Kimaaki – Marketplace de Delivery",
    description: "Conectamos você aos melhores estabelecimentos da sua região",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}